dist: bionic
language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - ocaml
      - libstdc++6
      - libgomp1
      - libgmp-dev
      - python
sudo: false
cache:
  directories:
    - $HOME/.opam
    - $HOME/jdk8

before_install:
- opam init --yes --no-setup --comp 4.08.0
- eval $(opam env)

install:
- opam install menhir ppx_sexp_conv sexplib dune ppx_let ppx_custom_printf yaml
- travis_wait 30 opam install z3

script: bash -ex .travis-ci.sh
