language: c
os:
  - "linux"
dist: "xenial"
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - ocaml
      - libstdc++6
      - libgomp1
      - libgmp-dev
      - python3-pip
      - python3-setuptools
cache:
  directories:
    - $HOME/.opam
    - $HOME/jdk8
script: bash -ex .travis-ci.sh
