package edu.kyoto.fos.regnant.translation;

/* For generating unique, temporary names. These names are guaranteed to be unique and reasonably
  descriptive. There is no difference between those generated by getBase and getField except for
  the human "readable" names used
 */
interface VarManager {
  String getBase();
  String getField();
}
